CC=pdflatex
BIB=bibtex

document: Raul_Reguillo_Carmona_Actividad_3.tex
	$(CC) Raul_Reguillo_Carmona_Actividad_3.tex

bib: Raul_Reguillo_Carmona_Actividad_3.aux Raul_Reguillo_Carmona_Actividad_3.tex
	$(BIB) Raul_Reguillo_Carmona_Actividad_3.aux
	$(CC) Raul_Reguillo_Carmona_Actividad_3.tex
	$(CC) Raul_Reguillo_Carmona_Actividad_3.tex
